--- Cargo.toml	2021-12-12 16:47:25.000000000 +0800
+++ Cargo.toml	2026-01-05 00:34:14.000000000 +0800
@@ -24,13 +24,13 @@
 authors = ["Nev Delap <nevdelap@gmail.com>"]
 
 [dependencies]
-ansi_term = "0.12.*"
-getopts = "0.2.*"
-glob = "0.3.*"
-libc = "0.2.*"
-regex = "1.5.*"
-time = "0.3.*"
-walkdir = "2.3.*"
+ansi_term = "0.12.1"
+getopts = "0.2.21"
+glob = "0.3.0"
+libc = "0.2.109"
+regex = "1.5.4"
+time = "0.3.5"
+walkdir = "2.3.2"
 
 [profile.release]
 lto = true
